### ISSUE TITLE
Add tests for notebooks

### ISSUE THREAD

**Issue by ksaur** [microsoft/vasim#53]
We have a lot of copy-pasted code in [the documentation notebook](https://github.com/microsoft/vasim/blob/main/examples/using_vasim.ipynb) and there may be additional code in the [examples](https://github.com/microsoft/vasim/blob/main/examples/) folder that we should add some tests for.

**Comment by bpkroth** [comment]
Something like this should work:

```sh
find . -name '*.ipynb' -print0 | xargs -0 -n1 -P0 python -m jupyter execute
if [ $? != 0 ]; then
    echo "ERROR: Notebooks execution failed." >&2
    exit 1
fi
```

See Also:
https://github.com/microsoft/MLOS/blob/main/Makefile#L644
