### ISSUE TITLE
Parallelize tests

### ISSUE THREAD

**Issue by bpkroth** [microsoft/vasim#60]
Investigate using `pytest-xdist` to parallelize tests.

**Comment by bpkroth** [comment]
Right now this doesn't work because multiple tests currently collide withone another's working directory when writing/deleting data from the filesystem.

This should probably be addressed through something like a `ContextManager` and `TempDirectory` that automatically cleanups up after itself.

**Comment by ksaur** [comment]
a stupidly easy way would just to name all of the test dirs differently

**Comment by bpkroth** [comment]
Yeah, that'd work for the tests.  But I didn't look into whether this was fundamentally preventing simultaneous runs across instances for other purposes too.
________________________________
