### ISSUE TITLE
Remove old `metadata.txt`

### ISSUE THREAD

**Issue by ksaur** [microsoft/vasim#73]
We switched metadata to always be `metadata.json`. However, we have some remants of `metadata.txt` lurking around when users set `save_config=True`.

We need to [delete this](https://github.com/microsoft/vasim/blob/d1b606f2b652d6c88bf57887cb9fe246477d4880/recommender/cluster_state_provider/PredictiveFileClusterStateProvider.py#L54) out, and [clean up](https://github.com/microsoft/vasim/blob/d1b606f2b652d6c88bf57887cb9fe246477d4880/recommender/cluster_state_provider/FileClusterStateProvider.py#L70) any remaining commented-out blocks.

**Comment by apavlen** [comment]
Done
